### ISSUE TITLE
Using just the checkboxes from this theme.

### ISSUE THREAD

**Issue by jan-Kulpas** [ashwinjadhav818/obsidian-aura#2]
Hi I wanted to add some checkbox variants to better work with the Tasks plugin. Is there any way to just borrow the checkboxes but keep obsidians default theme? Changing the entire UI seems like too big of an adjustment to me right now. (It looks really nice though! :wink:)

**Comment by ashwinjadhav818** [comment]
Sure here's the snippet, [Github Gist](https://gist.github.com/ashwinjadhav818/cc07566fef59a1eced33e0ed81dbeed7) 
Click this link and download this snippet in your <YourVault>/.obsidian/snippets folder
