### ISSUE TITLE
Low contrast in file picker for Origin and Default light color schemes

### ISSUE THREAD

**Issue by art-solopov** [ashwinjadhav818/obsidian-aura#3]
Here's how a file picker looks for me with the Origin light color scheme (some file names censored).

![Screenshot_20230905_022322](https://github.com/ZephyrsOS/obsidian-aura/assets/5079987/e1f58bec-9368-4c35-a6d7-cd1522f064f6)

You can barely see which item is selected.

**Comment by ashwinjadhav818** [comment]
Okay, I'll look into it when I get time.
