### ISSUE TITLE
Network usage is prohibited for themes

### ISSUE THREAD

**Issue by joethei** [ashwinjadhav818/obsidian-aura#4]
It appears that your theme uses network connections to load assets (e.g. fonts, icons, or images). This is prohibited by the official [Obsidian developer policies](https://docs.obsidian.md/Developer+policies) because themes should function completely locally.

You can bundle an asset for local use by using data URLs. [See this guide](https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme). 

Please let us know if you have any questions. Any themes that use network connections will be removed from the official directory in the first week of January 2024.

- The Obsidian team.

**Comment by ashwinjadhav818** [comment]
Hello Joethei,
I just updated my theme using the data URLs, but I had a problem that my theme has a lot of font import so the output file is getting around 62 mb. 
It is around a 63x increase in the file size.
![image](https://github.com/ashwinjadhav818/obsidian-aura/assets/81229115/2233c453-752f-44ae-ad05-7c6ed05ed5c1)

**Comment by ashwinjadhav818** [comment]
Removed the Fonts Selector Feature, so now the file size is around 2mb in the release 2.2.2. Hence closing this issue.
