### ISSUE TITLE
Cannot Access Settings Panel

### ISSUE THREAD

**Issue by Miko60** [ashwinjadhav818/obsidian-aura#5]
I just installed this theme, but I now cannot access the extreme left side of the frame where the setting button and all the other buttons are. I have the latest version and tried to correct the issue in sandbox, but nothing works.

**Comment by ashwinjadhav818** [comment]
Hi
Can you please explain the issue in detail and provide a screenshot for me to better understand it.

**Comment by Miko60** [comment]
As you can see in the attached screenshot, you can see the options column on the left side, with the New Note, New Folder tabs, search menu on top, etc. But there is no settings wheel and other configuration tabs to the left of that. So, I cannot access the settings menu, the graph button and all the other buttons on the extreme left of the screen. This happened right after I installed the Aura Theme.

Thank you...
________________________________

**Comment by ashwinjadhav818** [comment]
There is no attached screenshot where I can understand the issue. But I do not hide the settings button or change any UI element place in the theme. I guess it is some extension you installed.

**Comment by Miko60** [comment]
That might be the case. Don't know why you did not get the screenshot. Let me see if there are any extensions that are affecting it. Thanks so much for responding and I do like the theme.
________________________________
