### ISSUE TITLE
Update for Obsidian v1.6

### ISSUE THREAD

**Issue by Wayneoween** [ashwinjadhav818/obsidian-aura#6]
Thank you for your excellent work on the theme. I greatly appreciate the well-balanced colors and overall feel.

With the release of Obsidian v1.6 now publicly available, I noticed that several elements of the theme are not functioning as with v1.5. Specifically, the Files Tab/Files Browser.

I understand that theme updates can take time, especially with ongoing changes in Obsidian's development, and appreciate any efforts to address this.

**Comment by ashwinjadhav818** [comment]
Thank you, I have also noticed some bugs in the v1.6, I am a little busy in school right now, I will find some time and fix some of those bugs, can you describe all the bugs u found.

**Comment by Wayneoween** [comment]
Thanks! Mostly noticeable (and almost unusable) is the file browser. I'm not using too many other things so that's where I notice it mostly.

![image](https://github.com/ashwinjadhav818/obsidian-aura/assets/630640/459b1551-80ae-414e-8e8e-8602f1bb3cc5)

**Comment by ashwinjadhav818** [comment]
@Wayneoween The bugs I found in v1.6 were fixed in the v2.3.2 release. If you find any more bugs, please create a new issue.
Thank You
